#include "CodeGenerator.hpp"

#include <iomanip>

using namespace std;

CodeGenerator::CodeGenerator(AssemblyTarget target) : target_(target) {}

CodeGenerator::AssemblyTarget CodeGenerator::defaultTarget() {
#if defined(_WIN32)
    return AssemblyTarget::WindowsX64;
#elif defined(__APPLE__)
    return AssemblyTarget::MacOSX64;
#else
    return AssemblyTarget::LinuxX64;
#endif
}

bool CodeGenerator::isWindowsTarget() const {
    return target_ == AssemblyTarget::WindowsX64;
}

bool CodeGenerator::isMacOSTarget() const {
    return target_ == AssemblyTarget::MacOSX64;
}

string CodeGenerator::externalSymbol(const string &name) const {
    return isMacOSTarget() ? "_" + name : name;
}

string CodeGenerator::mainSymbol() const {
    return externalSymbol("main");
}

const vector<string> &CodeGenerator::argumentRegisters() const {
    static const vector<string> sysvRegisters = {"rdi", "rsi", "rdx",
                                                 "rcx", "r8",  "r9"};
    static const vector<string> windowsRegisters = {"rcx", "rdx", "r8", "r9"};
    return isWindowsTarget() ? windowsRegisters : sysvRegisters;
}

void CodeGenerator::emitCall(const string &symbol, bool external) {
    if (isWindowsTarget()) {
        text_ << "    sub rsp, 32\n";
    }
    text_ << "    call " << (external ? externalSymbol(symbol) : symbol) << "\n";
    if (isWindowsTarget()) {
        text_ << "    add rsp, 32\n";
    }
}

string CodeGenerator::generateAssembly(Program &program,
                                       const string &sourceName) {
    text_.str("");
    text_.clear();
    strings_.clear();
    floats_.clear();
    labelCounter_ = 0;
    stringCounter_ = 0;
    prepareFunctionLabels(program);

    text_ << "; Generated by SKKOA compiler\n";
    text_ << "; Source: " << sourceName << "\n\n";
    text_ << "global " << mainSymbol() << "\n";
    text_ << "extern " << externalSymbol("printf") << "\n\n";
    text_ << "extern " << externalSymbol("scanf") << "\n\n";
    text_ << "extern " << externalSymbol("malloc") << "\n";
    text_ << "extern " << externalSymbol("free") << "\n\n";
    text_ << "section .text\n";
    emitStringConcat();

    for (auto &function : program.functions) {
        emitFunction(*function);
    }
    emitMain(program);

    ostringstream output;
    output << "default rel\n\n";
    output << "section .data\n";
    output << "    fmt_int db \"%ld\", 10, 0\n";
    output << "    fmt_float db \"%f\", 10, 0\n";
    output << "    fmt_char db \"%c\", 10, 0\n";
    output << "    fmt_ptr db \"%p\", 10, 0\n";
    output << "    fmt_scan_int db \"%ld\", 0\n";
    output << "    fmt_scan_float db \"%lf\", 0\n";
    output << "    fmt_scan_char db \" %c\", 0\n";
    output << "    fmt_str db \"%s\", 10, 0\n";
    for (const auto &entry : strings_) {
        output << "    " << entry.label << " db " << bytesForString(entry.value)
               << ", 0\n";
    }
    output << dec << setprecision(17);
    for (const auto &entry : floats_) {
        output << "    " << entry.label << " dq " << entry.value << "\n";
    }
    output << "\n";
    output << text_.str();
    return output.str();
}

void CodeGenerator::prepareFunctionLabels(Program &program) {
    functionLabels_.clear();
    int index = 0;
    for (auto &function : program.functions) {
        functionLabels_[function->name] = "skkoa_fn_" + to_string(index++);
    }
}

CodeGenerator::FunctionContext
CodeGenerator::buildContext(const string &label, const vector<Param> &params,
                            const vector<unique_ptr<Stmt>> &body) {
    FunctionContext context;
    context.label = label;
    context.endLabel = label + "_end";

    int offset = 0;
    for (const auto &param : params) {
        offset += 8;
        context.locals[param.name] = {param.type, offset};
    }
    collectLocals(body, context, offset);
    context.stackSize = alignTo16(offset);
    return context;
}

void CodeGenerator::collectLocals(const vector<unique_ptr<Stmt>> &statements,
                                  FunctionContext &context, int &offset) {
    for (const auto &statement : statements) {
        collectLocalFromStmt(*statement, context, offset);
    }
}

void CodeGenerator::collectLocalFromStmt(const Stmt &statement,
                                         FunctionContext &context,
                                         int &offset) {
    if (auto *varDecl = dynamic_cast<const VarDeclStmt *>(&statement)) {
        if (context.locals.count(varDecl->name) == 0) {
            if (varDecl->type.isArray) {
                int bytes = varDecl->type.arraySize * 8;
                int baseOffset = offset + 8;
                offset += bytes;
                context.locals[varDecl->name] = {varDecl->type, baseOffset};
            } else {
                offset += 8;
                context.locals[varDecl->name] = {varDecl->type, offset};
            }
        }
    } else if (auto *ifStmt = dynamic_cast<const IfStmt *>(&statement)) {
        for (const auto &branch : ifStmt->branches) {
            collectLocals(branch.body, context, offset);
        }
        collectLocals(ifStmt->elseBody, context, offset);
    } else if (auto *whileStmt = dynamic_cast<const WhileStmt *>(&statement)) {
        collectLocals(whileStmt->body, context, offset);
    } else if (auto *repeatStmt = dynamic_cast<const RepeatStmt *>(&statement)) {
        if (context.locals.count(repeatStmt->iterator) == 0) {
            TypeName iteratorType;
            iteratorType.base = ValueType::Int;
            iteratorType.location = repeatStmt->location;
            offset += 8;
            context.locals[repeatStmt->iterator] = {iteratorType, offset};
        }
        collectLocals(repeatStmt->body, context, offset);
    }
}

int CodeGenerator::alignTo16(int value) const {
    if (value == 0) {
        return 0;
    }
    int remainder = value % 16;
    return remainder == 0 ? value : value + (16 - remainder);
}

void CodeGenerator::emitFunction(FunctionDecl &function) {
    string label = functionLabels_[function.name];
    FunctionContext context = buildContext(label, function.params, function.body);
    current_ = &context;

    text_ << "\n" << label << ":\n";
    emitPrologue(function.params, false);
    emitStatements(function.body);
    if (function.returnType.base == ValueType::Void) {
        text_ << "    mov rax, 0\n";
    }
    emitEpilogue();
    current_ = nullptr;
}

void CodeGenerator::emitMain(Program &program) {
    vector<Param> params;
    FunctionContext context = buildContext("main", params, program.mainStatements);
    current_ = &context;

    text_ << "\n" << mainSymbol() << ":\n";
    emitPrologue(params, true);
    emitStatements(program.mainStatements);
    text_ << "    mov rax, 0\n";
    emitEpilogue();
    current_ = nullptr;
}

void CodeGenerator::emitPrologue(const vector<Param> &params, bool isMain) {
    const vector<string> &registers = argumentRegisters();
    text_ << "    push rbp\n";
    text_ << "    mov rbp, rsp\n";
    if (current_->stackSize > 0) {
        text_ << "    sub rsp, " << current_->stackSize << "\n";
    }

    if (!isMain) {
        for (size_t i = 0; i < params.size() && i < registers.size(); i++) {
            const auto &slot = current_->locals[params[i].name];
            text_ << "    mov [rbp - " << slot.offset << "], " << registers[i]
                  << "\n";
        }
    }
}

void CodeGenerator::emitEpilogue() {
    text_ << current_->endLabel << ":\n";
    text_ << "    mov rsp, rbp\n";
    text_ << "    pop rbp\n";
    text_ << "    ret\n";
}

void CodeGenerator::emitStatements(const vector<unique_ptr<Stmt>> &statements) {
    for (const auto &statement : statements) {
        emitStatement(*statement);
    }
}

void CodeGenerator::emitStatement(const Stmt &statement) {
    if (auto *varDecl = dynamic_cast<const VarDeclStmt *>(&statement)) {
        emitVarDecl(*varDecl);
    } else if (auto *assignment = dynamic_cast<const AssignmentStmt *>(&statement)) {
        emitAssignment(*assignment);
    } else if (auto *expression = dynamic_cast<const ExpressionStmt *>(&statement)) {
        emitExpr(*expression->expression);
    } else if (auto *print = dynamic_cast<const PrintStmt *>(&statement)) {
        emitPrint(*print);
    } else if (auto *input = dynamic_cast<const InputStmt *>(&statement)) {
        emitInput(*input);
    } else if (auto *ifStmt = dynamic_cast<const IfStmt *>(&statement)) {
        emitIf(*ifStmt);
    } else if (auto *whileStmt = dynamic_cast<const WhileStmt *>(&statement)) {
        emitWhile(*whileStmt);
    } else if (auto *repeatStmt = dynamic_cast<const RepeatStmt *>(&statement)) {
        emitRepeat(*repeatStmt);
    } else if (auto *returnStmt = dynamic_cast<const ReturnStmt *>(&statement)) {
        emitReturn(*returnStmt);
    }
}

void CodeGenerator::emitVarDecl(const VarDeclStmt &statement) {
    auto slot = current_->locals.at(statement.name);
    if (statement.type.isArray) {
        return;
    }

    if (statement.initializer) {
        if (statement.type.base == ValueType::Float) {
            emitFloatExpr(*statement.initializer);
            text_ << "    movsd [rbp - " << slot.offset << "], xmm0\n";
        } else {
            emitExpr(*statement.initializer);
            text_ << "    mov [rbp - " << slot.offset << "], rax\n";
        }
    } else {
        text_ << "    mov qword [rbp - " << slot.offset << "], 0\n";
    }
}

void CodeGenerator::emitAssignment(const AssignmentStmt &statement) {
    if (statement.index) {
        emitArrayAddress(statement.name, *statement.index);
        text_ << "    push rax\n";
        emitExpr(*statement.value);
        text_ << "    pop rbx\n";
        text_ << "    mov [rbx], rax\n";
        return;
    }

    auto slot = current_->locals.at(statement.name);
    if (slot.type.base == ValueType::Float) {
        emitFloatExpr(*statement.value);
        text_ << "    movsd [rbp - " << slot.offset << "], xmm0\n";
    } else {
        emitExpr(*statement.value);
        text_ << "    mov [rbp - " << slot.offset << "], rax\n";
    }
}

void CodeGenerator::emitPrint(const PrintStmt &statement) {
    const vector<string> &registers = argumentRegisters();
    if (statement.expression->inferredType == ValueType::String) {
        emitExpr(*statement.expression);
        text_ << "    mov " << registers[1] << ", rax\n";
        text_ << "    lea " << registers[0] << ", [fmt_str]\n";
        text_ << "    xor eax, eax\n";
        emitCall("printf", true);
        return;
    }
    if (statement.expression->inferredType == ValueType::Float) {
        emitFloatExpr(*statement.expression);
        text_ << "    lea " << registers[0] << ", [fmt_float]\n";
        if (isWindowsTarget()) {
            text_ << "    movq " << registers[1] << ", xmm0\n";
            text_ << "    movq xmm1, " << registers[1] << "\n";
            text_ << "    xor eax, eax\n";
        } else {
            text_ << "    mov eax, 1\n";
        }
        emitCall("printf", true);
        return;
    }
    if (statement.expression->inferredType == ValueType::Char) {
        emitExpr(*statement.expression);
        text_ << "    mov " << registers[1] << ", rax\n";
        text_ << "    lea " << registers[0] << ", [fmt_char]\n";
        text_ << "    xor eax, eax\n";
        emitCall("printf", true);
        return;
    }
    if (statement.expression->inferredType == ValueType::Pointer) {
        emitExpr(*statement.expression);
        text_ << "    mov " << registers[1] << ", rax\n";
        text_ << "    lea " << registers[0] << ", [fmt_ptr]\n";
        text_ << "    xor eax, eax\n";
        emitCall("printf", true);
        return;
    }

    emitExpr(*statement.expression);
    text_ << "    mov " << registers[1] << ", rax\n";
    text_ << "    lea " << registers[0] << ", [fmt_int]\n";
    text_ << "    xor eax, eax\n";
    emitCall("printf", true);
}

void CodeGenerator::emitInput(const InputStmt &statement) {
    auto slot = current_->locals.at(statement.name);
    const vector<string> &registers = argumentRegisters();

    if (statement.index) {
        emitArrayAddress(statement.name, *statement.index);
        text_ << "    mov " << registers[1] << ", rax\n";
        text_ << "    lea " << registers[0] << ", [fmt_scan_int]\n";
    } else {
        text_ << "    lea " << registers[1] << ", [rbp - " << slot.offset
              << "]\n";
        if (slot.type.base == ValueType::Float) {
            text_ << "    lea " << registers[0] << ", [fmt_scan_float]\n";
        } else if (slot.type.base == ValueType::Char) {
            text_ << "    lea " << registers[0] << ", [fmt_scan_char]\n";
        } else {
            text_ << "    lea " << registers[0] << ", [fmt_scan_int]\n";
        }
    }
    text_ << "    xor eax, eax\n";
    emitCall("scanf", true);

    if (!statement.index && slot.type.base == ValueType::Bool) {
        text_ << "    mov rax, [rbp - " << slot.offset << "]\n";
        text_ << "    cmp rax, 0\n";
        text_ << "    setne al\n";
        text_ << "    movzx rax, al\n";
        text_ << "    mov [rbp - " << slot.offset << "], rax\n";
    }
}

void CodeGenerator::emitIf(const IfStmt &statement) {
    string endLabel = newLabel("if_end");
    vector<string> nextLabels;
    for (size_t i = 0; i < statement.branches.size(); i++) {
        nextLabels.push_back(newLabel("if_next"));
    }

    for (size_t i = 0; i < statement.branches.size(); i++) {
        emitExpr(*statement.branches[i].condition);
        text_ << "    cmp rax, 0\n";
        text_ << "    je " << nextLabels[i] << "\n";
        emitStatements(statement.branches[i].body);
        text_ << "    jmp " << endLabel << "\n";
        text_ << nextLabels[i] << ":\n";
    }

    emitStatements(statement.elseBody);
    text_ << endLabel << ":\n";
}

void CodeGenerator::emitWhile(const WhileStmt &statement) {
    string startLabel = newLabel("while_start");
    string endLabel = newLabel("while_end");

    text_ << startLabel << ":\n";
    emitExpr(*statement.condition);
    text_ << "    cmp rax, 0\n";
    text_ << "    je " << endLabel << "\n";
    emitStatements(statement.body);
    text_ << "    jmp " << startLabel << "\n";
    text_ << endLabel << ":\n";
}

void CodeGenerator::emitRepeat(const RepeatStmt &statement) {
    auto slot = current_->locals.at(statement.iterator);
    string startLabel = newLabel("repeat_start");
    string endLabel = newLabel("repeat_end");

    emitExpr(*statement.start);
    text_ << "    mov [rbp - " << slot.offset << "], rax\n";
    text_ << startLabel << ":\n";
    text_ << "    mov rax, [rbp - " << slot.offset << "]\n";
    text_ << "    sub rsp, 16\n";
    text_ << "    mov [rsp], rax\n";
    emitExpr(*statement.end);
    text_ << "    mov rbx, rax\n";
    text_ << "    mov rax, [rsp]\n";
    text_ << "    add rsp, 16\n";
    text_ << "    cmp rax, rbx\n";
    text_ << "    jg " << endLabel << "\n";
    emitStatements(statement.body);
    text_ << "    add qword [rbp - " << slot.offset << "], 1\n";
    text_ << "    jmp " << startLabel << "\n";
    text_ << endLabel << ":\n";
}

void CodeGenerator::emitReturn(const ReturnStmt &statement) {
    if (statement.value) {
        emitExpr(*statement.value);
    } else {
        text_ << "    mov rax, 0\n";
    }
    text_ << "    jmp " << current_->endLabel << "\n";
}

void CodeGenerator::emitExpr(const Expr &expression) {
    if (auto *literal = dynamic_cast<const IntLiteralExpr *>(&expression)) {
        text_ << "    mov rax, " << literal->value << "\n";
    } else if (auto *literal = dynamic_cast<const FloatLiteralExpr *>(&expression)) {
        string label = addFloatLiteral(literal->value);
        text_ << "    movq rax, [rel " << label << "]\n";
    } else if (auto *literal = dynamic_cast<const BoolLiteralExpr *>(&expression)) {
        text_ << "    mov rax, " << (literal->value ? 1 : 0) << "\n";
    } else if (auto *literal = dynamic_cast<const CharLiteralExpr *>(&expression)) {
        text_ << "    mov rax, " << literal->value << "\n";
    } else if (auto *literal = dynamic_cast<const StringLiteralExpr *>(&expression)) {
        string label = addStringLiteral(literal->value);
        text_ << "    lea rax, [" << label << "]\n";
    } else if (auto *variable = dynamic_cast<const VariableExpr *>(&expression)) {
        auto slot = current_->locals.at(variable->name);
        text_ << "    mov rax, [rbp - " << slot.offset << "]\n";
    } else if (auto *arrayAccess = dynamic_cast<const ArrayAccessExpr *>(&expression)) {
        emitArrayAddress(arrayAccess->name, *arrayAccess->index);
        text_ << "    mov rax, [rax]\n";
    } else if (auto *address = dynamic_cast<const AddressExpr *>(&expression)) {
        emitAddress(*address);
    } else if (auto *deref = dynamic_cast<const DereferenceExpr *>(&expression)) {
        emitExpr(*deref->pointer);
        text_ << "    mov rax, [rax]\n";
    } else if (auto *unary = dynamic_cast<const UnaryExpr *>(&expression)) {
        emitExpr(*unary->operand);
        if (unary->op == UnaryOp::Negate) {
            text_ << "    neg rax\n";
        } else {
            text_ << "    cmp rax, 0\n";
            text_ << "    sete al\n";
            text_ << "    movzx rax, al\n";
        }
    } else if (auto *binary = dynamic_cast<const BinaryExpr *>(&expression)) {
        if (binary->inferredType == ValueType::String && binary->op == BinaryOp::Add) {
            const vector<string> &registers = argumentRegisters();
            emitExpr(*binary->left);
            text_ << "    sub rsp, 16\n";
            text_ << "    mov [rsp], rax\n";
            emitExpr(*binary->right);
            text_ << "    mov " << registers[1] << ", rax\n";
            text_ << "    mov " << registers[0] << ", [rsp]\n";
            text_ << "    add rsp, 16\n";
            emitCall("skkoa_concat", false);
            return;
        }
        if ((binary->left->inferredType == ValueType::Float ||
             binary->right->inferredType == ValueType::Float) &&
            (binary->op == BinaryOp::Equal || binary->op == BinaryOp::NotEqual ||
             binary->op == BinaryOp::Less || binary->op == BinaryOp::LessEqual ||
             binary->op == BinaryOp::Greater || binary->op == BinaryOp::GreaterEqual)) {
            emitFloatExpr(*binary->left);
            text_ << "    sub rsp, 16\n";
            text_ << "    movsd [rsp], xmm0\n";
            emitFloatExpr(*binary->right);
            text_ << "    movsd xmm1, [rsp]\n";
            text_ << "    add rsp, 16\n";
            text_ << "    ucomisd xmm1, xmm0\n";
            switch (binary->op) {
            case BinaryOp::Equal:
                text_ << "    sete al\n";
                break;
            case BinaryOp::NotEqual:
                text_ << "    setne al\n";
                break;
            case BinaryOp::Less:
                text_ << "    setb al\n";
                break;
            case BinaryOp::LessEqual:
                text_ << "    setbe al\n";
                break;
            case BinaryOp::Greater:
                text_ << "    seta al\n";
                break;
            case BinaryOp::GreaterEqual:
                text_ << "    setae al\n";
                break;
            default:
                break;
            }
            text_ << "    movzx rax, al\n";
            return;
        }
        emitExpr(*binary->left);
        text_ << "    push rax\n";
        emitExpr(*binary->right);
        text_ << "    mov rbx, rax\n";
        text_ << "    pop rax\n";

        switch (binary->op) {
        case BinaryOp::Add:
            text_ << "    add rax, rbx\n";
            break;
        case BinaryOp::Subtract:
            text_ << "    sub rax, rbx\n";
            break;
        case BinaryOp::Multiply:
            text_ << "    imul rax, rbx\n";
            break;
        case BinaryOp::Divide:
            text_ << "    cqo\n";
            text_ << "    idiv rbx\n";
            break;
        case BinaryOp::Modulo:
            text_ << "    cqo\n";
            text_ << "    idiv rbx\n";
            text_ << "    mov rax, rdx\n";
            break;
        case BinaryOp::Equal:
            text_ << "    cmp rax, rbx\n";
            text_ << "    sete al\n";
            text_ << "    movzx rax, al\n";
            break;
        case BinaryOp::NotEqual:
            text_ << "    cmp rax, rbx\n";
            text_ << "    setne al\n";
            text_ << "    movzx rax, al\n";
            break;
        case BinaryOp::Less:
            text_ << "    cmp rax, rbx\n";
            text_ << "    setl al\n";
            text_ << "    movzx rax, al\n";
            break;
        case BinaryOp::LessEqual:
            text_ << "    cmp rax, rbx\n";
            text_ << "    setle al\n";
            text_ << "    movzx rax, al\n";
            break;
        case BinaryOp::Greater:
            text_ << "    cmp rax, rbx\n";
            text_ << "    setg al\n";
            text_ << "    movzx rax, al\n";
            break;
        case BinaryOp::GreaterEqual:
            text_ << "    cmp rax, rbx\n";
            text_ << "    setge al\n";
            text_ << "    movzx rax, al\n";
            break;
        case BinaryOp::And:
            text_ << "    cmp rax, 0\n";
            text_ << "    setne al\n";
            text_ << "    movzx rax, al\n";
            text_ << "    cmp rbx, 0\n";
            text_ << "    setne bl\n";
            text_ << "    movzx rbx, bl\n";
            text_ << "    and rax, rbx\n";
            break;
        case BinaryOp::Or:
            text_ << "    cmp rax, 0\n";
            text_ << "    setne al\n";
            text_ << "    movzx rax, al\n";
            text_ << "    cmp rbx, 0\n";
            text_ << "    setne bl\n";
            text_ << "    movzx rbx, bl\n";
            text_ << "    or rax, rbx\n";
            break;
        }
    } else if (auto *call = dynamic_cast<const CallExpr *>(&expression)) {
        const vector<string> &registers = argumentRegisters();
        if (call->name == "할당") {
            emitExpr(*call->arguments[0]);
            text_ << "    mov " << registers[0] << ", rax\n";
            emitCall("malloc", true);
            return;
        }
        if (call->name == "해제") {
            emitExpr(*call->arguments[0]);
            text_ << "    mov " << registers[0] << ", rax\n";
            emitCall("free", true);
            text_ << "    mov rax, 0\n";
            return;
        }
        for (const auto &argument : call->arguments) {
            emitExpr(*argument);
            text_ << "    push rax\n";
        }
        for (int i = static_cast<int>(call->arguments.size()) - 1; i >= 0; i--) {
            text_ << "    pop " << registers[i] << "\n";
        }
        emitCall(functionLabels_.at(call->name), false);
    }
}

void CodeGenerator::emitFloatExpr(const Expr &expression) {
    if (auto *literal = dynamic_cast<const FloatLiteralExpr *>(&expression)) {
        string label = addFloatLiteral(literal->value);
        text_ << "    movsd xmm0, [rel " << label << "]\n";
    } else if (auto *literal = dynamic_cast<const IntLiteralExpr *>(&expression)) {
        text_ << "    mov rax, " << literal->value << "\n";
        text_ << "    cvtsi2sd xmm0, rax\n";
    } else if (auto *literal = dynamic_cast<const CharLiteralExpr *>(&expression)) {
        text_ << "    mov rax, " << literal->value << "\n";
        text_ << "    cvtsi2sd xmm0, rax\n";
    } else if (auto *variable = dynamic_cast<const VariableExpr *>(&expression)) {
        auto slot = current_->locals.at(variable->name);
        if (slot.type.base == ValueType::Float) {
            text_ << "    movsd xmm0, [rbp - " << slot.offset << "]\n";
        } else {
            text_ << "    mov rax, [rbp - " << slot.offset << "]\n";
            text_ << "    cvtsi2sd xmm0, rax\n";
        }
    } else if (auto *unary = dynamic_cast<const UnaryExpr *>(&expression)) {
        emitFloatExpr(*unary->operand);
        if (unary->op == UnaryOp::Negate) {
            string label = addFloatLiteral(-1.0);
            text_ << "    movsd xmm1, [rel " << label << "]\n";
            text_ << "    mulsd xmm0, xmm1\n";
        }
    } else if (auto *binary = dynamic_cast<const BinaryExpr *>(&expression)) {
        emitFloatExpr(*binary->left);
        text_ << "    sub rsp, 16\n";
        text_ << "    movsd [rsp], xmm0\n";
        emitFloatExpr(*binary->right);
        text_ << "    movsd xmm1, [rsp]\n";
        text_ << "    add rsp, 16\n";
        switch (binary->op) {
        case BinaryOp::Add:
            text_ << "    addsd xmm1, xmm0\n";
            break;
        case BinaryOp::Subtract:
            text_ << "    subsd xmm1, xmm0\n";
            break;
        case BinaryOp::Multiply:
            text_ << "    mulsd xmm1, xmm0\n";
            break;
        case BinaryOp::Divide:
            text_ << "    divsd xmm1, xmm0\n";
            break;
        default:
            break;
        }
        text_ << "    movapd xmm0, xmm1\n";
    } else {
        emitExpr(expression);
        text_ << "    cvtsi2sd xmm0, rax\n";
    }
}

void CodeGenerator::emitAddress(const AddressExpr &expression) {
    auto slot = current_->locals.at(expression.name);
    if (expression.index) {
        emitArrayAddress(expression.name, *expression.index);
    } else {
        text_ << "    lea rax, [rbp - " << slot.offset << "]\n";
    }
}

void CodeGenerator::emitArrayAddress(const string &name, const Expr &index) {
    auto slot = current_->locals.at(name);
    emitExpr(index);
    text_ << "    shl rax, 3\n";
    text_ << "    lea rbx, [rbp - " << slot.offset << "]\n";
    text_ << "    sub rbx, rax\n";
    text_ << "    mov rax, rbx\n";
}

void CodeGenerator::emitStringConcat() {
    const vector<string> &registers = argumentRegisters();
    text_ << "\nskkoa_concat:\n";
    text_ << "    push rbp\n";
    text_ << "    mov rbp, rsp\n";
    text_ << "    push rbx\n";
    text_ << "    push rdi\n";
    text_ << "    push rsi\n";
    text_ << "    sub rsp, 64\n";
    text_ << "    mov [rbp - 32], " << registers[0] << "\n";
    text_ << "    mov [rbp - 40], " << registers[1] << "\n";
    text_ << "    mov rbx, " << registers[0] << "\n";
    text_ << "    xor rcx, rcx\n";
    text_ << ".skkoa_concat_len_a:\n";
    text_ << "    cmp byte [rbx + rcx], 0\n";
    text_ << "    je .skkoa_concat_len_b_start\n";
    text_ << "    inc rcx\n";
    text_ << "    jmp .skkoa_concat_len_a\n";
    text_ << ".skkoa_concat_len_b_start:\n";
    text_ << "    mov [rbp - 48], rcx\n";
    text_ << "    mov rbx, [rbp - 40]\n";
    text_ << "    xor rcx, rcx\n";
    text_ << ".skkoa_concat_len_b:\n";
    text_ << "    cmp byte [rbx + rcx], 0\n";
    text_ << "    je .skkoa_concat_alloc\n";
    text_ << "    inc rcx\n";
    text_ << "    jmp .skkoa_concat_len_b\n";
    text_ << ".skkoa_concat_alloc:\n";
    text_ << "    mov rax, [rbp - 48]\n";
    text_ << "    add rax, rcx\n";
    text_ << "    add rax, 1\n";
    text_ << "    mov " << registers[0] << ", rax\n";
    emitCall("malloc", true);
    text_ << "    mov [rbp - 56], rax\n";
    text_ << "    mov rdi, rax\n";
    text_ << "    mov rsi, [rbp - 32]\n";
    text_ << ".skkoa_concat_copy_a:\n";
    text_ << "    mov al, [rsi]\n";
    text_ << "    cmp al, 0\n";
    text_ << "    je .skkoa_concat_copy_b_start\n";
    text_ << "    mov [rdi], al\n";
    text_ << "    inc rsi\n";
    text_ << "    inc rdi\n";
    text_ << "    jmp .skkoa_concat_copy_a\n";
    text_ << ".skkoa_concat_copy_b_start:\n";
    text_ << "    mov rsi, [rbp - 40]\n";
    text_ << ".skkoa_concat_copy_b:\n";
    text_ << "    mov al, [rsi]\n";
    text_ << "    mov [rdi], al\n";
    text_ << "    cmp al, 0\n";
    text_ << "    je .skkoa_concat_done\n";
    text_ << "    inc rsi\n";
    text_ << "    inc rdi\n";
    text_ << "    jmp .skkoa_concat_copy_b\n";
    text_ << ".skkoa_concat_done:\n";
    text_ << "    mov rax, [rbp - 56]\n";
    text_ << "    add rsp, 64\n";
    text_ << "    pop rsi\n";
    text_ << "    pop rdi\n";
    text_ << "    pop rbx\n";
    text_ << "    pop rbp\n";
    text_ << "    ret\n";
}

string CodeGenerator::newLabel(const string &prefix) {
    return ".L_" + prefix + "_" + to_string(labelCounter_++);
}

string CodeGenerator::addStringLiteral(const string &value) {
    string label = "str_" + to_string(stringCounter_++);
    strings_.push_back({label, value});
    return label;
}

string CodeGenerator::addFloatLiteral(double value) {
    string label = "float_" + to_string(static_cast<int>(floats_.size()));
    floats_.push_back({label, value});
    return label;
}

string CodeGenerator::bytesForString(const string &value) const {
    ostringstream out;
    for (size_t i = 0; i < value.size(); i++) {
        if (i > 0) {
            out << ", ";
        }
        out << "0x" << hex << setw(2) << setfill('0')
            << static_cast<int>(static_cast<unsigned char>(value[i]));
    }
    if (value.empty()) {
        return "0";
    }
    return out.str();
}

string CodeGenerator::generateAstDump(const Program &program) {
    ostringstream out;
    out << "Program\n";
    for (const auto &function : program.functions) {
        out << "  Function " << function->name << " -> "
            << function->returnType.display() << "\n";
        for (const auto &param : function->params) {
            out << "    Param " << param.name << ": " << param.type.display()
                << "\n";
        }
        dumpStatements(function->body, out, 4);
    }
    out << "  Main\n";
    dumpStatements(program.mainStatements, out, 4);
    return out.str();
}

string CodeGenerator::binaryOpName(BinaryOp op) const {
    switch (op) {
    case BinaryOp::Add:
        return "+";
    case BinaryOp::Subtract:
        return "-";
    case BinaryOp::Multiply:
        return "*";
    case BinaryOp::Divide:
        return "/";
    case BinaryOp::Modulo:
        return "%";
    case BinaryOp::Equal:
        return "==";
    case BinaryOp::NotEqual:
        return "!=";
    case BinaryOp::Less:
        return "<";
    case BinaryOp::LessEqual:
        return "<=";
    case BinaryOp::Greater:
        return ">";
    case BinaryOp::GreaterEqual:
        return ">=";
    case BinaryOp::And:
        return "그리고";
    case BinaryOp::Or:
        return "또는";
    }
    return "?";
}

string CodeGenerator::unaryOpName(UnaryOp op) const {
    return op == UnaryOp::Negate ? "-" : "아님";
}

void CodeGenerator::dumpStatements(const vector<unique_ptr<Stmt>> &statements,
                                   ostringstream &out, int depth) const {
    for (const auto &statement : statements) {
        dumpStatement(*statement, out, depth);
    }
}

void CodeGenerator::dumpStatement(const Stmt &statement, ostringstream &out,
                                  int depth) const {
    string pad = indent(depth);
    if (auto *varDecl = dynamic_cast<const VarDeclStmt *>(&statement)) {
        out << pad << (varDecl->isConst ? "ConstDecl " : "VarDecl ")
            << varDecl->name << ": " << varDecl->type.display() << "\n";
        if (varDecl->initializer) {
            dumpExpr(*varDecl->initializer, out, depth + 2);
        }
    } else if (auto *assignment = dynamic_cast<const AssignmentStmt *>(&statement)) {
        out << pad << "Assignment " << assignment->name << "\n";
        if (assignment->index) {
            out << pad << "  Index\n";
            dumpExpr(*assignment->index, out, depth + 4);
        }
        dumpExpr(*assignment->value, out, depth + 2);
    } else if (auto *print = dynamic_cast<const PrintStmt *>(&statement)) {
        out << pad << "Print\n";
        dumpExpr(*print->expression, out, depth + 2);
    } else if (auto *input = dynamic_cast<const InputStmt *>(&statement)) {
        out << pad << "Input " << input->name << "\n";
        if (input->index) {
            out << pad << "  Index\n";
            dumpExpr(*input->index, out, depth + 4);
        }
    } else if (auto *expression = dynamic_cast<const ExpressionStmt *>(&statement)) {
        out << pad << "ExpressionStmt\n";
        dumpExpr(*expression->expression, out, depth + 2);
    } else if (auto *ifStmt = dynamic_cast<const IfStmt *>(&statement)) {
        out << pad << "If\n";
        for (const auto &branch : ifStmt->branches) {
            out << pad << "  Branch\n";
            dumpExpr(*branch.condition, out, depth + 4);
            dumpStatements(branch.body, out, depth + 4);
        }
        if (!ifStmt->elseBody.empty()) {
            out << pad << "  Else\n";
            dumpStatements(ifStmt->elseBody, out, depth + 4);
        }
    } else if (auto *whileStmt = dynamic_cast<const WhileStmt *>(&statement)) {
        out << pad << "While\n";
        dumpExpr(*whileStmt->condition, out, depth + 2);
        dumpStatements(whileStmt->body, out, depth + 2);
    } else if (auto *repeatStmt = dynamic_cast<const RepeatStmt *>(&statement)) {
        out << pad << "Repeat " << repeatStmt->iterator << "\n";
        out << pad << "  From\n";
        dumpExpr(*repeatStmt->start, out, depth + 4);
        out << pad << "  To\n";
        dumpExpr(*repeatStmt->end, out, depth + 4);
        dumpStatements(repeatStmt->body, out, depth + 2);
    } else if (auto *returnStmt = dynamic_cast<const ReturnStmt *>(&statement)) {
        out << pad << "Return\n";
        if (returnStmt->value) {
            dumpExpr(*returnStmt->value, out, depth + 2);
        }
    }
}

void CodeGenerator::dumpExpr(const Expr &expression, ostringstream &out,
                             int depth) const {
    string pad = indent(depth);
    if (auto *literal = dynamic_cast<const IntLiteralExpr *>(&expression)) {
        out << pad << "IntLiteral " << literal->value << "\n";
    } else if (auto *literal = dynamic_cast<const FloatLiteralExpr *>(&expression)) {
        out << pad << "FloatLiteral " << literal->value << "\n";
    } else if (auto *literal = dynamic_cast<const StringLiteralExpr *>(&expression)) {
        out << pad << "StringLiteral \"" << literal->value << "\"\n";
    } else if (auto *literal = dynamic_cast<const CharLiteralExpr *>(&expression)) {
        out << pad << "CharLiteral " << literal->value << "\n";
    } else if (auto *literal = dynamic_cast<const BoolLiteralExpr *>(&expression)) {
        out << pad << "BoolLiteral " << (literal->value ? "참" : "거짓") << "\n";
    } else if (auto *variable = dynamic_cast<const VariableExpr *>(&expression)) {
        out << pad << "Variable " << variable->name << "\n";
    } else if (auto *arrayAccess = dynamic_cast<const ArrayAccessExpr *>(&expression)) {
        out << pad << "ArrayAccess " << arrayAccess->name << "\n";
        dumpExpr(*arrayAccess->index, out, depth + 2);
    } else if (auto *address = dynamic_cast<const AddressExpr *>(&expression)) {
        out << pad << "Address " << address->name << "\n";
        if (address->index) {
            dumpExpr(*address->index, out, depth + 2);
        }
    } else if (auto *deref = dynamic_cast<const DereferenceExpr *>(&expression)) {
        out << pad << "Dereference\n";
        dumpExpr(*deref->pointer, out, depth + 2);
    } else if (auto *unary = dynamic_cast<const UnaryExpr *>(&expression)) {
        out << pad << "Unary " << unaryOpName(unary->op) << "\n";
        dumpExpr(*unary->operand, out, depth + 2);
    } else if (auto *binary = dynamic_cast<const BinaryExpr *>(&expression)) {
        out << pad << "Binary " << binaryOpName(binary->op) << "\n";
        dumpExpr(*binary->left, out, depth + 2);
        dumpExpr(*binary->right, out, depth + 2);
    } else if (auto *call = dynamic_cast<const CallExpr *>(&expression)) {
        out << pad << "Call " << call->name << "\n";
        for (const auto &argument : call->arguments) {
            dumpExpr(*argument, out, depth + 2);
        }
    }
}

string CodeGenerator::indent(int count) const {
    return string(static_cast<size_t>(count), ' ');
}
